### ISSUE TITLE
Regarding inference

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [alexander-pv/maskrcnn_tf2#10]
Hi,

I have noticed that you explicitly transferring the weights from training graph to inference graph. Would you please let me know the reason for the same?

Thanks,
Veeru.

**Comment by alexander-pv** [comment]
Hi, @VeeranjaneyuluToka,

Basically, training and inference graphs differ for MaskRCNN. The original matterport model has the same feature with a bit less verbosity.
Besides, such a way helps to port the model to .onnx.

You can consider these basic schemes for training and inference mode:
![mask_rcnn_training_mode](https://user-images.githubusercontent.com/30959770/146561858-c4d65d74-a23e-4297-a67e-91c309684a15.png)

![mask_rcnn_inference_mode](https://user-images.githubusercontent.com/30959770/146562005-6e276594-0a9d-41a6-b308-39a4f1fbcada.png)
