### ISSUE TITLE
minimize_mask in utils

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [alexander-pv/maskrcnn_tf2#12]
Hi, 

Looks like minimize_mask function definition is missed in common.utils, when i enable minimize_mask, it gives the below error

 File "C:\Users\veeru\Downloads\source\maskrcnn_tf2-master\src\preprocess\preprocess.py", line 245, in __getitem__
    proc_masks = utils.minimize_mask(bboxes, proc_masks, self.kwargs['mini_mask_shape'])

AttributeError: module 'common.utils' has no attribute 'minimize_mask'

Is the feature yet to be added?

Thanks,
Veeru.

**Comment by alexander-pv** [comment]
Hi, @VeeranjaneyuluToka,
Thanks for the issue! It was rather a bug. Now mini masks work.
