### ISSUE TITLE
typo in training script

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [alexander-pv/maskrcnn_tf2#14]
Hi @alexander-pv ,

I think i found a kind of typo in training.py, it is as below

    train_datagen = tf.data.Dataset.from_generator(generator=make_gen_callable(train_dataloader),
                                                   output_types=tuple(tf.float32 for _ in range(out_len)))
    val_datagen = tf.data.Dataset.from_generator(generator=make_gen_callable(**train_dataloader**),
                                                 output_types=tuple(tf.float32 for _ in range(out_len)))

I believe highlighted one should be val_dataloader.

**Comment by alexander-pv** [comment]
Hi,
Thanks! Problem solved.
