### ISSUE TITLE
EfficientNet layers to extract feature maps

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [alexander-pv/maskrcnn_tf2#6]
Hi Again, i have one more question on the feature maps extraction from the efficientnet backbone especially. You have chosen self.backbone_outputs.update(
            {f'efficientnetb{i}': ['block2a_activation', 'block3a_expand_activation',
                                   'block4a_expand_activation', 'block6a_expand_activation',
                                   'top_activation'] for i in range(8)}
        )
layers to extract features. Would you mind sharing the reason to choose these layers. I have chosen 
C1:block1c_add
C2:block2f_add
C3:block3f_add
C4:block5h_add
C5:block7c_add

but results are not that good. So eager to know if there is anything that we need to look before we choose these layers to extract feature maps.

Thanks,
Veeru.

**Comment by alexander-pv** [comment]
Hi, @VeeranjaneyuluToka,

The feature maps were chosen based on the idea not to modify at first the project much for a specific backbone to keep quite an understandable code structure. Based on this limitation I made some training tests with a balloon and coco-mini datasets and got the best results with the backbone outputs named above.

I think, the key to improving model results is to configure FPN specifically to each backbone. I already added such a task to `TODO` list. If you'll get some interesting results, please, let me know.
