### ISSUE TITLE
Computing steps per epoch in dataloader

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [alexander-pv/maskrcnn_tf2#9]
Hi,

Looks like you are dividing the training samples twice by batch_size to get steps_per_epoch

self.steps_per_epoch = self.__len__() // self.batch_size

And inside __len__() as well. Is not it? I suppose it should be once.

Thanks,
Veeru.

**Comment by alexander-pv** [comment]
Hi, @VeeranjaneyuluToka,
Thank you for opening the issue. 
Now it is fixed, the number of steps per epoch is calculated only in dunder len method.
